AWSTemplateFormatVersion: '2010-09-09'
Description: >
  ECS Fargate (ALB) para api-students (Flask + SQLite, puerto 8000).
  Usa únicamente el rol existente LabRole que trae AWS Academy.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: ID de la VPC (usa la Default VPC)
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Dos subnets de la VPC (separadas por coma)
  ImageUri:
    Type: String
    Description: URI de la imagen en ECR (ej. 123456789012.dkr.ecr.us-east-1.amazonaws.com/api-students:latest)
  LabRoleArn:
    Type: String
    Description: arn:aws:iam::<TU_ACCOUNT_ID>:role/LabRole  (reemplaza con tu Account ID)
  DesiredCount:
    Type: Number
    Default: 1
  ContainerPort:
    Type: Number
    Default: 8000

Resources:
  # --- Seguridad
  ALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG del ALB
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ServiceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG del servicio ECS
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref ContainerPort
          ToPort: !Ref ContainerPort
          SourceSecurityGroupId: !Ref ALBSG

  # --- Load Balancer
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups: [!Ref ALBSG]
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: !Ref ContainerPort
      Protocol: HTTP
      TargetType: ip
      VpcId: !Ref VpcId
      HealthCheckPath: /
      Matcher:
        HttpCode: 200-399

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # --- Logs (opcional pero útil)
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/api-students
      RetentionInDays: 7

  # --- ECS
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: api-students-cluster

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      RequiresCompatibilities: [FARGATE]
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      ExecutionRoleArn: !Ref LabRoleArn   # usa el LabRole existente
      TaskRoleArn: !Ref LabRoleArn        # permisos para la app (mínimos via LabRole)
      ContainerDefinitions:
        - Name: api-students
          Image: !Ref ImageUri
          Essential: true
          PortMappings:
            - ContainerPort: !Ref ContainerPort
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  Service:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: !Ref Cluster
      DesiredCount: !Ref DesiredCount
      LaunchType: FARGATE
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref SubnetIds
          SecurityGroups: [!Ref ServiceSG]
      LoadBalancers:
        - TargetGroupArn: !Ref TargetGroup
          ContainerName: api-students
          ContainerPort: !Ref ContainerPort

Outputs:
  ALBDNSName:
    Description: DNS público del Application Load Balancer
    Value: !GetAtt ALB.DNSName
